### ISSUE TITLE
JavaScript代码块中格式化错误

### ISSUE THREAD

**Issue by zhuoyan** [sumnow/markdown-formatter#1]
### before
``` js
var str = '中文';
```
### after
``` js
var str = '中文‘;
```

中文输入法情况下 格式化失败。

**Comment by sumnow** [comment]
[](非常感谢提出的问题,已经在0.3.0版本修复,详情查看[这里](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md))
