### ISSUE TITLE
文档中的代码块有没有配置项可以关掉格式化

### ISSUE THREAD

**Issue by busyrat** [sumnow/markdown-formatter#10]
代码块之外的部分格式化效果还行，但是代码块内就很乱了，如果能像 vetur 那就最好了

比如就不用格式化了

```
\`\`\` html
<div>htllo</div>
\`\`\`
```

**Comment by sumnow** [comment]
代码块只会格式化类别为html,css,js的语言,如果你不想格式化该区域,只要设置为其他语言类型例如

``` vue
<template>
    <div></div>
</template>
```

**Comment by sumnow** [comment]
您好,代码块格式化现在依赖对语言类型的声明,例如

    ``` code
    function(){console.log(123)}
    ```

是不会格式化的,只有code为`js`,`html`,或者`css`时候才会格式化

详情可以参考[这里](https://github.com/sumnow/markdown-formatter/blob/master/README_CN.md#%E4%BB%A3%E7%A0%81%E5%8C%BA),已在[0.6.1]((https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#061))版本更新
