### ISSUE TITLE
关于部分标点符号的替换的小问题

### ISSUE THREAD

**Issue by lartpang** [sumnow/markdown-formatter#11]
# 关于部分标点符号的替换的小问题

如果原始的中文符号句号后有两个空格, 转换后会导致符号后面有两个空格, 可否始终保持一个空格?

原文：

```
一个空格， 两个空格，  一个空格。 两个空格。  补充文字。
一个空格，两个空格，一个空格。两个空格。补充文字。
```

格式化之后：

```
一个空格, 两个空格, 一个空格. 两个空格.  补充文字.
一个空格, 两个空格, 一个空格. 两个空格. 补充文字.
```

另外对于顿号的格式化问题，英文没有顿号，如果替换，是否可以替换为逗号。或者您可以考虑使用半角逗号。

原文：

```
阿双方就大家、阿里山的房间了，按时到廊坊……。
```

格式化之后（顿号后面还多了一个空格）：

```
阿双方就大家、 阿里山的房间了, 按时到廊坊…….
```

**Comment by sumnow** [comment]
非常感谢您提出的问题。
这个问题已经在 `0.6.7` 版本中修复, 点击[这里](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#067)查看。
顿号格式化的问题，您需要在`markdownFormatter.fullWidthTurnHalfWidth`属性中，添加`、`，例如从原属性值"，：；！“”‘’（）？。"改为"，、：；！“”‘’（）？。"
