### ISSUE TITLE
格式化错误

### ISSUE THREAD

**Issue by Zt448143356** [sumnow/markdown-formatter#12]
before：
![image](https://user-images.githubusercontent.com/48010552/66640945-66549680-ec4c-11e9-8e1e-814d30e07fc1.png)

after：
![image](https://user-images.githubusercontent.com/48010552/66641000-7cfaed80-ec4c-11e9-8723-05eda0fd2891.png)

格式化错误

**Comment by sumnow** [comment]
您好,您的问题已经在 [0.7.5](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#075) 版本修复.
感谢您的反馈
