### ISSUE TITLE
bad formatting for dots

### ISSUE THREAD

**Issue by Ardeshir81** [sumnow/markdown-formatter#13]
HI!
Thanks for this nice add-on.
Everything is great except this sentence: 
`in certain situations: Logging in, calling apis, etc ... . For this to work you can`
on format turns to this:
`in certain situations: Logging in, calling apis, etc .... For this to work you can`

But there is a difference. I want that space on my dots.

**Comment by sumnow** [comment]
Thank you for your question, which has been fixed in version [0.7.6](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md#076)
