### ISSUE TITLE
列表接着一级标题格式化出错

### ISSUE THREAD

**Issue by lancerXXXX** [sumnow/markdown-formatter#16]
- 描述
    - 我在写一个列表之后跟着一个一级标题
    - 例如
         - 1.a
         - 2.b
         然后空一行 跟着一个一级标题  # 标题  
格式化就会变成    2.b# 标题  
就是标题哪一行和列表最后一行接在一起了

**Comment by sumnow** [comment]
该问题已经在[0.7.9](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#079)版本修复.
谢谢您的反馈
