### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by szhielelp** [sumnow/markdown-formatter#17]
markdown-formatter 里面似乎没有中英文之间添加空格的功能?

建议集成 Doctor Jones: https://github.com/Leopoldthecoder/doctor-jones

**Comment by uptonking** [comment]
@sumnow    
中英文间添加空格，有人需要，有人不需要，希望不要作为默认行为，，，  
若一定要添加功能，请作为一个config option提供，类似 `cjkSpacing: preserve/always`
