### ISSUE TITLE
引用下的表格

### ISSUE THREAD

**Issue by lancerXXXX** [sumnow/markdown-formatter#20]
- 格式化之前
![image](https://user-images.githubusercontent.com/42160297/73345160-86bd6500-42be-11ea-9912-a3d1de62635b.png)
- 格式化之后
![image](https://user-images.githubusercontent.com/42160297/73345204-9f2d7f80-42be-11ea-9f01-362ddb4b5bce.png)
把第一列的`<`也当成表格的一部分

**Comment by sumnow** [comment]
您好,这个问题已经在[0.8.4](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#084)版本修复
