### ISSUE TITLE
Formatter converts style of unordered lists

### ISSUE THREAD

**Issue by BoltonBailey** [sumnow/markdown-formatter#21]
When I create an unordered list I do it like this

```
* foo
  * bar
    * baz
  * quux
```

The formatter converts this to

```
* foo
  + bar
    - baz
  + quux
```

But this is caught by the markdown linter
> MD004/ul-style: Unordered list style [Expected: asterisk; Actual: dash]markdownlint(MD004)

Is there a way to make the formatter not change the asterisks?

**Comment by BoltonBailey** [comment]
Note that you can change the markdownlint settings to accept this by adding 
```
    "markdownlint.config": {
        "MD004": {
            "style": "sublist"
        },
        "MD013": false
    }
```
to settings.json. It would still be nice to know how to fix this.

**Comment by sumnow** [comment]
adding 
```
 "markdownFormatter.formatULSymbol": true
```

to `settings.json` .
