### ISSUE TITLE
Formatting adds a "*" to Markdown Rules

### ISSUE THREAD

**Issue by tifDev** [sumnow/markdown-formatter#23]
If you format a bolder rule:
`- - - - - - -`

It will become:
`* - - - - - -`

And this changes completely the markdown output.

**Comment by sumnow** [comment]
I'm sorry about this issue.
The problem has been fixed in the [0.8.0](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md#080) version. Thank you.
