### ISSUE TITLE
怎么关闭这个默认＋空格的功能

### ISSUE THREAD

**Issue by zybieku** [sumnow/markdown-formatter#27]
![image](https://user-images.githubusercontent.com/15903330/80318267-91df4d00-883b-11ea-9345-78740b9e7cfa.png)
如上图,img src里面的 .  格式化的时候默认被加入了空格,图片就展示不出来. 还有域名也会被加入空格,我想关闭这个,还是说我直接把格式化的功能给关闭比较好

**Comment by HuuLane** [comment]
可以试试这个

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by sumnow** [comment]
您好,这个问题已经在[0.8.3](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#083)版本修复
