### ISSUE TITLE
[Error Format]:TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by tifDev** [sumnow/markdown-formatter#28]
I'm getting this error on VS code 1.44.2 in Ubuntu. It used to work well, i don't know what is happening...

**Comment by ahmadmoawad** [comment]
Yes, I have this issue also in windows

**Comment by buledong** [comment]
Yes, I have this issue also in windows

**Comment by sumnow** [comment]
Sorry, this issue has been fixed in version [0.8.5](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md#085).

**Comment by tifDev** [comment]
Thank you
