### ISSUE TITLE
错误地加转义符号 \

### ISSUE THREAD

**Issue by violetu** [sumnow/markdown-formatter#29]
![image](https://user-images.githubusercontent.com/33022132/83482394-c72e2900-a4d2-11ea-990e-4250a9b5454d.png)

一格式化就给我有些地方的符号加转义符，不知道为啥？
难道是我 markdown 语法哪里不规范？

**Comment by sumnow** [comment]
我做了尝试,没有办法复现您的问题,方便贴一段会出问题的代码吗

**Comment by violetu** [comment]
> 我做了尝试,没有办法复现您的问题,方便贴一段会出问题的代码吗

可否给个邮箱，我把 md 文件发给你。

一段代码不会出现那样的问题貌似，整体多了之后，才会出现这个问题。

**Comment by sumnow** [comment]
很抱歉对您的影响, 该问题已经在0.8.8版本修复

**Comment by violetu** [comment]
谢谢
