### ISSUE TITLE
搞不懂为什么要把全角符号改为半角的

### ISSUE THREAD

**Issue by iostalks** [sumnow/markdown-formatter#3]
如果是写中文，改成半角的得多难受。。

这是可选项我知道，但为什么全角的符号，后面还会自动插入空格，而且还不支持自定义……

**Comment by yunhaixu** [comment]
> 如果是写中文，改成半角的得多难受。。
> 
> 这是可选项我知道，但为什么全角的符号，后面还会自动插入空格，而且还不支持自定义……

个人感觉半角更合适吧，全角的话 我写一部分中文一部分英文，似乎有点不一致吧。

**Comment by sumnow** [comment]
您好, 关于写中文中, 使用半角符号的问题, 我主要参考了一些知乎的回答.

1. [为什么很多人喜欢在中文文章中使用英文标点呢？](https://www.zhihu.com/question/20248581/answer/175085550)
2. [為什麼你發言寫文時使用的標點符號都是英文半角呢？是刻意為之嗎？](https://www.zhihu.com/question/19981206/answer/13550846)

此外, 在学术论文中也流行, 将中文标点的句号换为点号.

至于全角的句号后, 插入一个空格, 确实应该是可省略的. 这个可选配置已经在0.4.3版本加入了, 感谢你的反馈.

**Comment by iostalks** [comment]
赞，感谢作者。
