### ISSUE TITLE
Formatter adds trailing space between backticks and newlines, which conflicts with Markdown linters

### ISSUE THREAD

**Issue by ddejohn** [sumnow/markdown-formatter#31]
`some code-highlighted text\n` changes to `some code-highlighted text \n` which Markdown linters then complain about.

I personally also don't like the change of padding code-highlighted segments with whitespace in general and would like to disable this feature.

**Comment by ddejohn** [comment]
Update: formatter also inconsistently fixes headers:

https://i.imgur.com/ObEVYeH.png

**Comment by sumnow** [comment]
lt has been fixed in [0.8.7](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md#087)
