### ISSUE TITLE
格式化md里面的代码时，有bug

### ISSUE THREAD

**Issue by zhangdaren** [sumnow/markdown-formatter#32]
比如下面的代码

``` js
$ npm install miniprogram-to-uniapp - g
```

放在md里面进行格式化时，，好家伙，变成这样的~~

``` js
$ npm install miniprogram - to - uniapp - g
```

我。。。。

**Comment by sumnow** [comment]
因为你使用了js的格式化,

![image](https://user-images.githubusercontent.com/23467500/86901589-692eda00-c13f-11ea-881f-ff7db7d6f449.png)

实际上,应该使用bash

![image](https://user-images.githubusercontent.com/23467500/86901652-7f3c9a80-c13f-11ea-9ba0-0e75799f11c7.png)

``` BASH
# BASH
npm install miniprogram-to-uniapp - g
```

**Comment by zhangdaren** [comment]
噢噢。。。原来是这样啊，感谢大佬~&nbsp;

不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mervin"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 下午5:22
收件人: "sumnow/markdown-formatter"<markdown-formatter@noreply.github.com&gt;; 
抄送: "张鹏"<375890534@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sumnow/markdown-formatter] 格式化md里面的代码时，有bug (#32)





 
因为你使用了js的格式化,
 

 
实际上,应该使用bash
 

 # BASH npm install miniprogram-to-uniapp - g
