### ISSUE TITLE
Space remove in case of list entry ending with code

### ISSUE THREAD

**Issue by fruh** [sumnow/markdown-formatter#36]
In case of the list item end with code `, the new line is removed.

Expected behavior:
![image](https://user-images.githubusercontent.com/5055828/93434155-0fc5f280-f8c8-11ea-9cef-b5348bab312e.png)

Actual behavior (see line number 7): 
![image](https://user-images.githubusercontent.com/5055828/93434217-25d3b300-f8c8-11ea-9f8d-71670b9a5a90.png)

**Comment by sumnow** [comment]
I'm sorry about this issue.
It has been fixed in the 0.8.9 version. Thank you.
