### ISSUE TITLE
Formatting issue in shell/bash code block

### ISSUE THREAD

**Issue by tifDev** [sumnow/markdown-formatter#38]
Hello,

See this example:

## Assign command output to a variable 

``` bash
#!/bin/bash 
SERVER_NAME=`hostname`
echo "You are running this script on ${SERVER_NAME}." 

# Output: You are running this script on linuxsvr. 
```

After format, it adds a space after the "=" like this:
```
SERVER_NAME= `hostname`
```
And this is invalid in shell/bash.

Could you stop this behaviour for bash codeblock pls?

Thanks for your extension.

Regards,
Tif

**Comment by sumnow** [comment]
You can use code block,  like 

![image](https://user-images.githubusercontent.com/23467500/104291122-1bcc6480-54f6-11eb-86f0-6e404fd9f373.png)
