### ISSUE TITLE
格式化序号有bug

### ISSUE THREAD

**Issue by nonoSword08** [sumnow/markdown-formatter#45]
格式化前：
![image](https://user-images.githubusercontent.com/49900070/110229275-40b3e580-7f43-11eb-8f4c-7f3ad15d0238.png)

格式化后：
![image](https://user-images.githubusercontent.com/49900070/110229291-51645b80-7f43-11eb-9c9d-4d7c906ce4cb.png)

只有这段出现了该情况，其他的列表都正常工作了。

还有可否出个配置项来关闭序号补零这个功能。

**Comment by sumnow** [comment]
这个问题, 已经在0.9.1版本修复, 感谢您的反馈
