### ISSUE TITLE
Spaces being added forever between comma and snippet

### ISSUE THREAD

**Issue by Mearman** [sumnow/markdown-formatter#48]
1. Create a markdown file
2. Create a bullet point, followed by a comma and a code snippet
3. e.g.: 
```{r}
* word,`code`
```
4. Run format code
5. The formatted will repeatably insert more and more spaces between the comma and start of the snippet eg:
```{r}
* word,               `code`
```

**Comment by sumnow** [comment]
I'm sorry about this issue.
It has been fixed in the [0.9.1](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md#091) version. Thank you.
