### ISSUE TITLE
yaml code blocks get formatted

### ISSUE THREAD

**Issue by Paul-Aime** [sumnow/markdown-formatter#49]
Due to its syntax similar to markdown, `yaml` code blocks are formatted as if there are markdown lines, even though if have `    "markdownFormatter.formatCodes": false` in my `settings.json`.

So the following file:

    a:
      - b
      - c:
        - d 
    
    ```yaml
    a:
      - b
      - c:
        - d 
    ```
      
    ```python
    a:
      - b
      - c:
        - d 
    ```

will be wrongly formatted as follows:
      
    a:
    
      + b
      + c:
        - d
    
    ``` yaml
    a:
    
      + b
      + c:
        - d
    
    ```
    
    ``` python
    a:
    
      + b
      + c:
        - d
    
    ```

**Comment by sumnow** [comment]
I'm sorry about this issue.
It has been fixed in the [0.9.3](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG.md#093) version. Thank you.
