### ISSUE TITLE
对于引用区域的格式化是否可以控制不要添加多余的行？

### ISSUE THREAD

**Issue by lartpang** [sumnow/markdown-formatter#6]
![image](https://user-images.githubusercontent.com/26847524/61938021-bfece380-afc2-11e9-8d5d-235702c390b4.png)
格式化后就变成这样了，显示出来的结果就会断开。
![image](https://user-images.githubusercontent.com/26847524/61938054-c9764b80-afc2-11e9-9731-55228d556d51.png)

**Comment by sumnow** [comment]
非常感谢提出的问题,已经在0.5.4版本修复,详情查看[这里](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#054)
