### ISSUE TITLE
关于嵌套的连接的格式化问题

### ISSUE THREAD

**Issue by lartpang** [sumnow/markdown-formatter#7]
格式化之后是这样的：
![image](https://user-images.githubusercontent.com/26847524/61938144-fc204400-afc2-11e9-8331-5fa87c017a96.png)
但我本身是这样的：

```
[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
```

**Comment by sumnow** [comment]
非常感谢提出的问题,已经在0.5.4版本修复,详情查看[这里](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#054)
