### ISSUE TITLE
格式化操作会破坏`markdown-all-in-one`插件生成的目录

### ISSUE THREAD

**Issue by lartpang** [sumnow/markdown-formatter#8]
![image](https://user-images.githubusercontent.com/26847524/61993257-8dfb8000-b09b-11e9-8134-d1758af4e3f7.png)

格式化后：

![image](https://user-images.githubusercontent.com/26847524/61993269-a4a1d700-b09b-11e9-96af-6d11e445c9fe.png)

所以目前只好先格式化，再添加目录呢。不知道有什么好的解决办法么？

**Comment by sumnow** [comment]
您好，这个问题是因为 `markdown all in one` 插件中的列表前空格数目不通导致的错误，我参照了[markdownlint](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md007---unordered-list-indentation)，将插件列表的空格也统一成了2个，现在格式化不会出现问题了。
谢谢您的反馈。
已经在[0.5.5](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#055)版本中修复
