### ISSUE TITLE
格式化操作会破坏原有链接

### ISSUE THREAD

**Issue by lartpang** [sumnow/markdown-formatter#9]
示例文本：

```
* <https://onedrive.live.com/redir?resid=F3A8A31ABFAC51B0!256&authkey=!AC4-yOEjn0bgrCQ&ithint=file%2crar>

* 下载: Please download from [OneDrive](https://1drv.ms/u/s!ApwdOxIIFBH19TzDv7nRfH5ZsMNL) or [Baiduyun](http://pan.baidu.com/s/1bQ4yHC).
```

格式化之后

* <https://onedrive.live.com/redir?resid=F3A8A31ABFAC51B0!256&authkey=! AC4-yOEjn0bgrCQ&ithint=file%2crar>

* 下载: Please download from [OneDrive](https://1drv.ms/u/s! ApwdOxIIFBH19TzDv7nRfH5ZsMNL) or [Baiduyun](http://pan.baidu.com/s/1bQ4yHC).

可以看到，在某些感叹号之后断开了。

**Comment by sumnow** [comment]
您好，这个问题已经在[0.5.5](https://github.com/sumnow/markdown-formatter/blob/master/CHANGELOG_CN.md#055)版本中修复.
感谢您的反馈
